### ISSUE TITLE
GE-tests

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#1219]
## Graphical Editor Tests

Graphical editor tests run locally on linux and windows, but still have issues when running on the build server.

When running with maven add profile "ge-tests" to enable tests.  Use -Dtest=_ExampleTest_ to run single test.

Issue Notes:
* Linux window focus behavior and window manager.
* Must mouse move, press, release when simulating mouse.
* Cannot rename elements that have the same location consecutively.

**Comment by philip-alldredge** [comment]
Tests can fail on windows due to coordinates being incorrect. One cause is that the AWT robot takes into account the coordinate system of the display and HiDPI.  How the coordinate is determined is not. A workaround until we decide the best way to handle is to display UI scaling by passing the following to the JVM.
-Dsun.java2d.uiScale=1.0
