### ISSUE TITLE
Error and warning icon decorations in AADL Navigator are not updated

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1824]
## Summary

The error decorations in the navigator should reflect error markers on the resource.

## Expected and Current Behavior

When an error is fixed in an aadl file the error decoration in the navigator should be updated, but this does not happen.

## Steps to Reproduce

1. Introduce and fix errors in an aadl file
2. Observe decorations in the navigator
3. Navigator is refreshed on selecting the file of refreshing the navigator via F5.

## Environment

* **OSATE Version**: 2.5.0
* **Operating System**: Ubuntu 19.04

**Comment by AaronGreenhouse** [comment]
Need to figure out how to trigger a refresh in the common navigator.

I see an odd thing in the `plugin.xml` for `org.osate.ui`.   Note the `viewerRefresher` in the definition of the `AadlNavigator`:

```
	<extension
         point="org.eclipse.ui.navigator.viewer">
		<viewerContentBinding 
            viewerId="org.osate.ui.navigator.AadlNavigator">
			<includes>
   				<contentExtension pattern="org.eclipse.ui.navigator.resources.workingSets" />
				<contentExtension pattern="org.eclipse.ui.navigator.resourceContent" />     	      
				<contentExtension pattern="org.eclipse.ui.navigator.resources.filters.*"/>
    			<contentExtension pattern="org.osate.ui.navigator.contributedAadl" />
			    <contentExtension pattern="org.osate.ui.navigator.aadlProjectDependencies" />
    			<contentExtension pattern="org.osate.ui.navigator.aadlFileContent" />
			    <contentExtension pattern="org.osate.ui.navigator.menuActions" />
				<contentExtension pattern="org.osate.ui.navigator.AadlNavigatorLinkHelper" />
    <contentExtension
          pattern="org.osate.ui.navigator.viewerRefresher">
    </contentExtension>
			</includes>
		</viewerContentBinding>
  		<viewerActionBinding
        	viewerId="org.osate.ui.navigator.AadlNavigator">
     		<includes>
     			<actionExtension pattern="org.eclipse.ui.navigator.resources.*" />
     			<actionExtension pattern="org.osate.ui.navigator.*" />
     		</includes>
	  </viewerActionBinding>
   </extension>
```

The problem is there is no mention of this any where else.  The name doesn't seem to be bound to anything.

**Comment by AaronGreenhouse** [comment]
The Eclipse forum here may be useful, but the original question seems to be imcompletely answered: https://www.eclipse.org/forums/index.php/t/154948/

**Comment by AaronGreenhouse** [comment]
These seems more helpful: https://subscription.packtpub.com/book/application_development/9781783287796/1/ch01lvl1sec09/common-navigator

**Comment by AaronGreenhouse** [comment]
Made `AadlElementContentProvider` an `IResourceChangeListener`.  It forces a refresh of the associated viewer when a change event comes through.

I tried to make the refresh "smart" and only update the viewer when .aadl files are changed, but that didn't work because all the events that came thorugh just indicated that the workspace root had changed.  So it didn't make sense to do any fancy checking.
