### ISSUE TITLE
Refactored methods have lower visibility

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1869]
I rely on methods formerly in OsateResourceUtil, some of which have been deleted, others have been made private. 

In the short term, making `getInstanceModelURI` public again will meet my needs.

 In the long term, could you formalize API support so it is easier to know when to expect refactoring?

**Comment by lwrage** [comment]
We usually mark methods as deprecated first with a note that they will be removed in the next release. You should look for such warnings on your code so you can intervene before the removal happens if necessary.

Some method removals are in preparation of properly versioning the API. We try to get rid of a lot of utility methods that are leftovers from OSATE1 (as in OsateResourceUtil) and provide limited value (like the save method in OsateResourceUtil).

**Comment by joeseibel** [comment]
`getInstanceModelURI` is now in `InstantiateModel` and has been made public in #1849. You can find the method here: https://github.com/osate/osate2/blob/f9132e3443d62005167557f6cc14a0194a7fd94d/core/org.osate.aadl2.instantiation/src/org/osate/aadl2/instantiation/InstantiateModel.java#L514

**Comment by smithdtyler** [comment]
Is this change already in the nightly build? Our canary build has been failing with a compilation error.

**Comment by joeseibel** [comment]
Yes, since it is in the `master` branch. You will need to change the call from `OsateResourceUtil.getInstanceModelURI` to `InstantiateModel.getInstanceModelURI`.

**Comment by smithdtyler** [comment]
In the future would it be possible to leave the old method in place with an @Deprecated annotation for one release cycle?
