### ISSUE TITLE
Graphical Editor rename fails when I type the letter "H"

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1999]
## Summary
1. I created a new package diagram using the New -> AADL Package -> Diagram Editor.
1. I created a new Abstract Type
1. I slow-clicked on it to change its name. Whenever I type the letter "H" the Abstract Type disappears. 

## Environment

* **OSATE Version**: 2.5.2 vFinal
* **Operating System**: Windows 10

**Comment by smithdtyler** [comment]
Best guess is that "H" is a mnemonic for "Hide" that is enabled when I select an element in the GUI but should be disabled when entering text.

**Comment by philip-alldredge** [comment]
@smithdtyler closing. This was fixed in #1992. It's unfortunate that this slipped into the release.  The resolution was to change the key binding to hide. I believe it is Ctrl-Shift-H now. There wasn't a practical way to prevent the key from being active when renaming. The work around is to right click on the element in the diagram editor or in the outline and select rename.
