### ISSUE TITLE
Flow latency analysis window is not sized based on content

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2039]
The Flow Latency Analysis window is not sized based on content. On Windows systems which have a window scaling > 100%, buttons are cut off or hidden.  Additionally, the window is not resizable so it is impossible to access those buttons.

## Environment

* **OSATE Version**: 2.5.2
* **Operating System**:  Windows 10

**Comment by philip-alldredge** [comment]
@lwrage I just noticed this was mislabeled. This is not an issue with the graphical editor's flow tools. This is related to the size of the window that appears when performing the latency analysis.

**Comment by AaronGreenhouse** [comment]
@philip-alldredge I'm trying to fix this, but I have a Mac, so I am not experiencing your problem and can only guess at it.  Are you saying that the scaling is causing the contents of the window to be clipped to the borders of the window?  This sounds like an SWT problem because in my snooping around of the Dialog/Shell/Window, it is supposed to be getting the size of the dialog contents and setting the dialog bounds accordingly.  

Can you attach a screen shot of the problem?

It is easy enough to change the dialog to face the RESIZE flag, but strange that it should be  necessary.

**Comment by philip-alldredge** [comment]
@AaronGreenhouse I'm away from my office computer so it's hard for me to reproduce at the moment. It only affects systems with certain DPI settings. The resize would definitely resolve the issue for me. A scrollbar would also work if there are any cases where the window wouldn't fit on a screen(Seems unlikely on modern displays).

**Comment by AaronGreenhouse** [comment]
@lwrage Was able to reproduce on Linux. 

I found settings on OS X for changing magnification, but I was able to cause layout problems by using it.

Below are screen shots from Lutz:

![144dpi.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/2b6abf77-6e08-474c-9edc-29db94eeb6d8)!

[120dpi.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/ef719b7e-0cee-4535-9f3a-57e3b4068263)

![96dpi.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/ce4b7445-6ee3-4e15-9ac1-43e4b516df3b)

**Comment by AaronGreenhouse** [comment]
I fixed this I hope.  
1. Made the dialog resizable.
2. Put the main content in a scroll panel.  This was a little tricky, because the straightforward thing to do, that is, get the preferred size of the work panel and then put it in the scroller can make things look funny.  Normally via the layout managers we expand the size of the work area to fit the preferred size of the window, but that doesn't work once you put in the work area inside a scroll pane.  So it might be too narrow, and then looks odd because there is a chunk of blank space to the right size of the dialog.  So I had to add a listener to the scroll pane that catches when it is resized and then expands the width/height of the work area to fill the initial size of the scroller.  Then it listener removed itself.  This captures the initial sizing of the window only.
