### ISSUE TITLE
Check for null containing classifier in Aadl2LinkingService::getLinkedObjects

### ISSUE THREAD

**Issue by brlarson** [osate/osate2#2139]
## Summary
When linking inside an annex library, a NullPointerException is thrown because
line 224:  ```aadl
Classifier ns = AadlUtil.getContainingClassifier(context);```
returns null, because there is no containing classifier for an annex library.

Please check for (ns  != null) before use and return an empty list instead (line 249)
```aadl
  if (ns != null)
    {
    EObject searchResult = AadlUtil.findNamedElementInList(ns.getAllFeatures(), name);
    if (searchResult != null && searchResult instanceof Port)
      {
      return Collections.singletonList(searchResult);
      }
    }
  return Collections.<EObject> emptyList();
```

## Environment

* **OSATE Version**:  2.6.1
* **Operating System**: macOS 10.14.6

**Comment by lwrage** [comment]
The implementation of `Aadl2LinkingService.getLinkedObjects()` assumes in many places that it is only called in the context of core AADL. The name resolution for references inside any annex  must happen in an annex specific linking service. 
The real bug is that the Aadl2Linking service tries to resolve inside an annex if no annex linking service is registered instead of just returning an empty list for any reference in an annex without an annex linking service.
