### ISSUE TITLE
Classifier information view is not updated when AADL text is edited and saved

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2435]
## Summary

Changes in AADL text files should be reflected in the classifier information view immediately after saving.

## Expected and Current Behavior

The only way to refresh the classifier information view is to re-open the classifier from the outline view.

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: all

**Comment by AaronGreenhouse** [comment]
Need to add resource change listener that watches the resources that contain all the classifiers in the hierarchy.  Listener should rebuild the view when a resource changes.

**Comment by AaronGreenhouse** [comment]
Added a resource change listener.  Changed the view to keep track of the URI of the classifier it is viewing.  When any resource changes that we care about, then the view is rebuild from the object referenced by the URI.  Need to keep the URI and not the Classifier object so that we can get the *newly parsed* Classifier object from the URI.
