### ISSUE TITLE
Open classifier information view from more places

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2439]
## Summary

The classifier information view can only be opened from the outline view when the classifier is selected. There are more places where the classifier can be determined from the selection. It should be possible to open the classifier with such a selection.  

## Expected and Current Behavior

It should be possible to open the classifier information view when

- a classifier is selected in the navigator
- an element referencing a classifier is selected in the navigator or outline view
- a component instance is selected in the navigator, outline view, or instance editor
- an element referencing a component instance is selected
- from the text editor

There should be a keyboard shortcut for this.

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: Win10

**Comment by keh181** [comment]
The Open Classifier Information view now supports the following: 

- Alt+C shortcut for Windows/Linux and Option+C for MacOS
- Prototypes and Subcomponents open referenced classifier if there is one, otherwise opens classifier that it is a part of
- Parameters, Data Ports, Feature Groups, and Access now show related classifier if one is provided
