### ISSUE TITLE
Implementation labels in outline view are too long

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2443]
## Summary

The label text shown in the outline view is often so long that the name of the element is cut off at the right.

## Expected and Current Behavior

The fixed text part of the label, e.g., _Subprogram Group Impl_, or _Flow Implementation_ should be shortened to allow more space for the name.

Is it possible to use an icon decoration (like the navigator uses for project type, etc.) to indicate that something is an implementation?

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: all

**Comment by lwrage** [comment]
Start with a list of current labels. Where do they come from?

**Comment by asazonova** [comment]
I know at some point we have talked about adding set of images with "i" in it for implementation elements. As far as I remember, we wanted to keep those images, I don't believe it was merged in any other issue\pr. I assume those images should stay under this branch. Is that correct? Or do we not need those additional images anymore, since we have moved on to image decorator solution

**Comment by asazonova** [comment]
You have also mentioned that label should not be shortened in other view (I believe it was a Semantic Model Outline view), is that correct?
