### ISSUE TITLE
Remove binpacker from ALISA

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2463]
When invoking the binpacker from ALISA, and the system is not schedulable, the following code is triggered
	
./analyses/org.osate.analysis.resource.management/src/org/osate/analysis/resource/management/handlers/Binpack.java:        org.osate.ui.dialogs.Dialog.showError(Application Binding Results",

this results in a window popping up with an error message.

This corresponds to the folloing ALISA verification method

	method ResourceAllocationScheduling : "Allocate threads to processors and assure schedulability." [
		plugin BinPack
		category Quality.Timing
		description
				"Bind all threads to processors while maintaining schedulability and meeting binding constraints. This analysis uses a BinPacking technique by Dio DeNiz."
	]

**Comment by joeseibel** [comment]
The binpacker does not produce any results that ALISA can use. The binpacker uses a dialog to give all of the results and ALISA looks for problem markers, which means that ALISA has no way of knowing if the binpacking was sucessful or if it had failed. Since we are planning on rewriting the binpacker, it doesn't make sense to fix bugs in the current implementation. Therefore, we are going to remove binpacking support from ALISA. The binpacker will still be available as a standard analysis from the Analyses menu.
