### ISSUE TITLE
Layout exception is thrown for self loops on the same side

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#2674]
**Summary**
An ELK exception is thrown when layout is performed on a diagram set to "Enable Layout Based on Direction" with two input features that are connected by a flow path with it's label shown.

**Steps To Reproduce**
1. Open the diagram for Classifier "c"
2. Show the label for Flow Path "fs" by using the Properties view.
3. Select "Window" -> "Preferences" -> "OSATE" -> "AADL Diagram Editor" -> "Enable Layout Based on Direction"
4. Right-click Classifier "c" and select "Layout" -> "Layout Diagram"

```aadl
package pkg
public

	abstract c
	features
		f2: in feature;
		f1: in feature;
	flows
		fs: flow path f1 -> f2;
end c;
	
end pkg;
```

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.2
 - Operating System: Windows 10

**Comment by philip-alldredge** [comment]
@RyanMcilnay I created an issue to the ELK project at https://github.com/eclipse/elk/issues/763

The issue can likely occur anytime we are using fixed position and connections. This can happen when working with feature groups because we do a second pass layout with fixed positions.  I will submit a pull request that will prevent layout of connection labels under such circumstances.
