### ISSUE TITLE
No internal Update of the ressources

### ISSUE THREAD

**Issue by Korny666** [osate/osate2#637]
When invoking the Model-statistics the result is always the same. There is no update visible.
Change an aadl file and invoke again. The values are still the same.
Files are changed on disk.

**Comment by reteprelief** [comment]
The analysis actually does not examine the model, just prints out a programmed in result.

Just kidding.

Are you saving the file after a change?
If you have created an instance model, did you re-instantiate the instance? Otherwise, the instance data does not change.
If you look at the result in the report (Excel file), did you close the file and reopen it? Excel does not do an auto-reload of a file when it changes in the file system.

I did a simple example test with two aadl files and added a declaration into one. Rerunning the model statistics picks up the change for me.
